[workspace]
members = ["kyd", "kyctl", "kyberos-protocol"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Alistair Lynn <alistair@alynn.co.uk>"]

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "forbid"
