[package]
name = "kyberos-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "kyberos_protocol"

[dependencies]
rmp-serde = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

