name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Protobuf
        run: sudo apt-get install -y protobuf-compiler

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: "rustfmt, clippy"

      - name: Check code formatting with Rustfmt
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings -D clippy::pedantic

      - name: Run Tests
        run: cargo test
